#!/usr/bin/env lua

local Ycur = 0          -- current ypos of turtle
local Ymax = 0          -- max ypos of turtle
local Ymin = 0          -- min ypos of turtle
local POSFILE = "/ypos.log"
local TIMEOUT = 10
local MASTERS = nil      -- allowed to control the turtle

function save_pos()
    f = fs.open(POSFILE, "w")
    f.write(Ycur)
    f.close()
end

function load_pos()
    if fs.exists(POSFILE) then
        f = fs.open(POSFILE, "r")
        Ycur = f.read()
        f.close()
        return Ycur
    else
        return nil
    end
end



-- main routine here
gs_rednet.init()
MASTERS = rednet_masters_load()

while 1 do
    sender,msg,dist = rednet.receive(TIMEOUT)
    if msg==nil then
        -- do nothing
    else
        if helpers.contains(MASTERS, sender) then
            -- allowed to control the turtle
        end
    end
end
