#!/usr/bin/env lua
-- Tankt turtle aus allen Slots nach

local slotcount = 16

-- Prüfe ob Turtle einen Namen hat
if not os.getComputerLabel() then
  print ("Turtle hat keinen Namen. Treibstoff ginge verloren.")
  print ("Zuerst einen Namen vergeben mit: 'label set [name]'")
  os.error(1)
end

print ("Treibstoff jetzt: "..turtle.getFuelLevel())
-- Nachtanken
print ("Suche Treibstoff in "..slotcount.." Slots.")
for i = 1,slotcount do
  turtle.select(i)
  if turtle.refuel() then
    print (" - Slot "..i.." / "..turtle.getFuelLevel())
  end
end
--
print ("Treibstoff jetzt: "..turtle.getFuelLevel())
