#!/usr/bin/env lua

-- material slots
local boden = 1
local waende = 2

function beladungsinfo()
    local t = {}
    t[boden] = "Bodenplatten"
    t[waende] = "Wände/Decke"
    tfuncs.beladung(t)
end

print("Graebt eine Roehre und dichtet alle Loecher mit Material ab.")
beladungsinfo()

-- get information from user
write("Tunnel Breite (x)? ")
x = tonumber(io.read())
write("Tunnel Hoehe (y)? ")
y = tonumber(io.read())
write("Tunnel Laenge (z)? ")
z = tonumber(io.read())

-- start digging
dig2.roehre(x,y,z)
